-- ===========================================================================
-- 003 — Blacklist Geomed: proprietários que não podem ser cadastrados
--
-- ESPELHO de src/db.js, bloco "BLACKLIST GEOMED". O app aplica isto sozinho na
-- inicialização; este arquivo existe para ser lido e para poder ser rodado à
-- mão no SQL Editor do Supabase. Ver sql/migrations/README.md.
--
-- IDEMPOTENTE: pode rodar quantas vezes for.
--
-- PARA DESFAZER (apaga a lista de bloqueios — não há como recuperar):
--   DROP TABLE IF EXISTS blacklist;
-- ===========================================================================

-- Tabela PRÓPRIA, e não uma coluna "bloqueado" em proprietarios: o bloqueio
-- chega ANTES do cadastro. A diretoria manda bloquear um CPF que nunca foi
-- cadastrado — justamente para que não seja. Uma coluna exigiria inventar um
-- proprietário sem nome, sem telefone e sem cadastro nenhum só para ter onde
-- marcar o bit.
--
-- O documento é guardado SÓ COM DÍGITOS, porque é assim que ele é comparado: o
-- mesmo CNPJ chega "12.345.678/0001-95" de um lado e "12345678000195" do
-- outro, e um bloqueio que falha por causa de pontuação é pior do que bloqueio
-- nenhum.
CREATE TABLE IF NOT EXISTS blacklist (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  documento       text NOT NULL,        -- CPF ou CNPJ do proprietário, só dígitos
  nome            text,                 -- como a pessoa é conhecida (ajuda a conferir)
  bloqueado_por   text NOT NULL,        -- quem DECIDIU (lista de src/blacklist.js)
  motivo          text NOT NULL,
  criado_por      text,                 -- e-mail de quem DIGITOU no Portal
  criado_em       text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  liberado_em     text,                 -- preenchido no desbloqueio; a linha fica
  liberado_por    text,
  liberado_motivo text
);

-- Um bloqueio ATIVO por documento. Parcial de propósito: o mesmo CPF pode ter
-- sido bloqueado, liberado e bloqueado de novo — o histórico são várias
-- linhas, e só a atual conta.
CREATE UNIQUE INDEX IF NOT EXISTS idx_blacklist_ativo
  ON blacklist (documento) WHERE liberado_em IS NULL;

-- O histórico de um documento (as linhas já liberadas), para a tela.
CREATE INDEX IF NOT EXISTS idx_blacklist_documento
  ON blacklist (documento);

-- A tabela nasce no schema "public", que o Supabase publica na API HTTP.
-- O bloco de sql/habilitar-rls.sql roda na inicialização do app e cobre toda
-- tabela nova; aqui vai explícito para quem rodar este arquivo à mão.
ALTER TABLE public.blacklist ENABLE ROW LEVEL SECURITY;
